# Copyright (C) 2005 - 2021 Settlers Freaks <sf-team at siedler25.org>
#
# SPDX-License-Identifier: GPL-2.0-or-later

version: 1.0.{build}
branches:
  only:
  - master
  
image: Visual Studio 2019

configuration:
  - Debug
  - Release
  
platform:
  - Win32
  - x64
    
environment:
  global:
    BOOST_DIR: 'C:\Libraries\boost_1_73_0'
    RTTR_DISABLE_ASSERT_BREAKPOINT: 1

install:
  - git clone https://github.com/Return-To-The-Roots/libutil.git libutil
  - git clone https://github.com/Return-To-The-Roots/libendian.git libendian
  - set CMAKE_PREFIX_PATH=%CMAKE_PREFIX_PATH%;%cd%\libutil;%cd%\libendian

before_build:
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 16 2019" -A %platform% -DRTTR_ENABLE_WERROR=ON -DBOOST_ROOT="%BOOST_DIR%" ..
    
build_script: cmake --build . --config %configuration% --parallel 4

test_script: ctest --output-on-failure -C %configuration% --parallel 4

